[package]
name = "platinum-armbian-bsp"
description = "Адаптер Armbian Build для board-specific BSP артефактов Platinum OS One"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
platinum-board.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
