[package]
name = "platinum-image"
description = "Описание разметки дисковых образов Platinum OS One"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
